<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!-- DEFINICIÓN DEL TIPO DE DOCUMENTO -->
<!DOCTYPE cartelera [
<!-- DEFINICIÓN DE ELEMENTOS --><!ELEMENT cartelera (película)*>
<!ELEMENT película (título , título_original? , nacionalidad , género , (clasificación | sin_clasificar) , sinopsis , director , reparto , web? , cartel?)>
<!ELEMENT título (#PCDATA)>
<!ELEMENT título_original (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT género (#PCDATA)>
<!ELEMENT clasificación EMPTY>
<!ELEMENT sin_clasificar EMPTY>
<!ELEMENT sinopsis (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT reparto (actor)+>
<!ELEMENT web (#PCDATA)>
<!ELEMENT cartel (#PCDATA)>
<!ELEMENT actor (#PCDATA)>
<!-- Definición de atributos --><!ATTLIST película código ID #REQUIRED>
<!ATTLIST película duración CDATA "">
<!ATTLIST película año CDATA "2003">
<!ATTLIST clasificación edad (8 | 12 | 16 | 18 | tp) #REQUIRED>
]>
<!-- *************************************************** -->
<cartelera>  
  <película código="p1" duración="152" año="2002">  
    <título>AQUELLAS JUERGAS UNIVERSITARIAS</título>  
    <título_original>Old School</título_original>  
    <nacionalidad>Estados Unidos</nacionalidad>  
    <género>Comedia</género>  
    <clasificación edad="tp"/>  
    <sinopsis>  
      Mitch, Frank y Beanie son tres amigos treintañeros cuyas vidas no son exactamente lo que
      esperaban. Mitch tiene una novia ninfómana que se mete en la cama con el primero que
      agarra. Frank se ha casado y su matrimonio nada  
      tiene que ver con las juergas salvajes que organizaban años atrás. Y Beanie es  
      un padre de familia que se muere por recuperar su alocada juventud. Pero las cosas cambian
      cuando Beanie sugiere que creen su propia fraternidad, en la nueva casa que Mitch tiene
      junto al campus de la universidad. Una ocasión para revivir tiempos gloriosos, hacer nuevos
      amigos y de volver a sus viejas, salvajes y desmadradas juergas de estudiantes.  
    </sinopsis>  
    <director>Todd Philips</director>  
    <reparto>  
      <actor>Luke Wilson</actor>  
      <actor>Will Farrel</actor>  
      <actor>Vince Vaughn</actor>  
    </reparto>  
    <web>http://www.uip.es</web>  
    <cartel>caratulas/Aquellas juergas.jpg</cartel>  
  </película>  
  <película código="p17" duración="06">  
    <título>EL ORO DE MOSCÚ</título>  
    <nacionalidad>España</nacionalidad>  
    <género>Comedia</género>  
    <sin_clasificar/>  
    <sinopsis>  
      Por una extraña coincidencia del destino, alguien recibe una información extraconfidencial de
      un anciano en sus últimos segundos de vida: el secreto mejor guardado de la Historia. El
      receptor, un trabajador de hospital, se lo comunica secretamente a un supuesto amigo.
      Ambos inician una aventura rocambolesca y llena de misterio. Ante la inutilidad de sus
      intentos y muy a  
      su pesar, tienen que recurrir a otras personas que así mismo van cayendo en el pozo sin
      fondo que conlleva descifrar el enigma.  
    </sinopsis>  
    <director>Jesús Bonilla</director>  
    <reparto>  
      <actor>Jesús Bonilla</actor>  
      <actor>Santiago Segura</actor>  
      <actor>Alfredo Landa</actor>  
      <actor>Concha Velasco</actor>  
      <actor>Antonio Resines</actor>  
      <actor>Gabino Diego, María Barranco</actor>  
      <actor>María Barranco</actor>  
    </reparto>  
  </película>  
</cartelera>
